# Generated by Django 4.2.7 on 2023-11-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('starship_class', models.CharField(max_length=100, verbose_name='Class')),
                ('value_when_new', models.CharField(max_length=100, verbose_name='Value when wew')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('max_atmosphering_speed', models.IntegerField(verbose_name='Length')),
                ('hyperdrive_capacity', models.IntegerField(verbose_name='Hyperdrive Capacity')),
                ('min_crew', models.IntegerField(verbose_name='Minimum Crew Compliment')),
                ('max_crew', models.IntegerField(verbose_name='Maximum Crew Compliment')),
                ('passengers', models.IntegerField(verbose_name='Maximum Passenger Capacity')),
                ('cargo_capacity', models.IntegerField(verbose_name='Maximum Cargo Capacity')),
                ('consumables_for', models.CharField(max_length=100, verbose_name='Name')),
                ('mglt', models.IntegerField(verbose_name='Maximum Speed')),
            ],
        ),
    ]
